name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Validate Shell Scripts
      run: |
        # Check for syntax errors in shell scripts
        find . -name "*.sh" -exec bash -n {} \;

    - name: Check Permissions
      run: |
        # Verify all shell scripts have executable permissions
        find . -name "*.sh" -exec chmod +x {} \;
        find . -name "*.sh" -exec test -x {} \; || echo "Error: Some scripts are not executable"

    - name: Run Interactive Mode Test
      run: |
        # Test interactive mode
        ./devtooly.sh --help
        
    - name: Check Configuration
      run: |
        # Verify configuration files exist and are valid
        test -f .devtooly/config.json
        test -f src/core/utils/constants.sh
        test -f src/core/utils/helpers.sh

    - name: Check Module Structure
      run: |
        # Verify all module directories exist
        test -d src/modules/languages
        test -d src/modules/editors
        test -d src/modules/databases
        test -d src/modules/containers
        test -d src/modules/devtools
        test -d src/modules/utilities

    - name: Check Documentation
      run: |
        # Verify essential documentation files exist
        test -f README.md
        test -f CONTRIBUTING.md
        test -f LICENSE
        test -f CODE_OF_CONDUCT.md

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Test Installation
      run: |
        # Test a sample installation
        ./devtooly.sh --dry-run
        
    - name: Check Logs
      run: |
        # Verify logs are created and have expected content
        test -d logs
        ls logs/*.log | grep -q "devtooly_"
